ALTER TABLE users
DROP COLUMN username;

ALTER TABLE users
ADD COLUMN firstname VARCHAR(255);

ALTER TABLE users
ADD COLUMN lastname VARCHAR(255);

ALTER TABLE users
ADD CONSTRAINT unique_email UNIQUE(email);
